import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/NavBar"; // ✅ add this import
import { AuthProvider } from "@/context/AuthContext";
import AuthRedirect from "@/context/AuthRedirect";
const geistSans = Geist({
  variable: "--font-geist-sans",

  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",

  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AuthRedirect>
            <NavBar />

            {children}
          </AuthRedirect>
        </AuthProvider>
      </body>
    </html>
  );
}
